
```{r}
library(dplyr)
library(ggplot2)
source("funs.R")
```



```{r}
load("MIMICIV_ARDS_IV_Berlin.RData")

load("MIMICIV_ARDS_IV_New.RData")

load("MIMICIV_ARDS_IV_Combined.RData")

load("MIMICIV_ARDS_Supp.RData")

```


```{r}
MIMICIV_ARDS_IV_Both <- MIMICIV_ARDS_IV_Combined[MIMICIV_ARDS_IV_Combined$ARDS_PF != "No" & MIMICIV_ARDS_IV_Combined$ARDS_SF != "No", ]

```


```{r}
character_func(MIMICIV_ARDS_IV_Both)
```
 
 
```{r}
MIMICIV_ARDS_IV_Non <- MIMICIV_ARDS_IV_Combined[MIMICIV_ARDS_IV_Combined$ARDS_PF == "No" & MIMICIV_ARDS_IV_Combined$ARDS_SF == "No", ]

```

```{r}
character_func(MIMICIV_ARDS_IV_Non)
```


```{r}
MIMICIV_IV_Berlin_ARDS <- MIMICIV_ARDS_IV_Combined[MIMICIV_ARDS_IV_Combined$ARDS_PF != "No" & MIMICIV_ARDS_IV_Combined$ARDS_SF == "No", ]

MIMICIV_IV_New_ARDS <- MIMICIV_ARDS_IV_Combined[MIMICIV_ARDS_IV_Combined$ARDS_PF == "No" & MIMICIV_ARDS_IV_Combined$ARDS_SF != "No", ]
```




```{r}
character_func(MIMICIV_IV_Berlin_ARDS)

```


```{r}
character_func(MIMICIV_IV_New_ARDS)
```

```{r}
MIMICIV_Supp_ARDS <- MIMICIV_ARDS_Supp[MIMICIV_ARDS_Supp$ARDS != "No", ]

MIMICIV_Supp_Non <- MIMICIV_ARDS_Supp[MIMICIV_ARDS_Supp$ARDS == "No", ]
```



```{r}
character_func(MIMICIV_Supp_ARDS)
```


```{r}
character_func(MIMICIV_Supp_Non)
```







```{r}
MIMICIV_ARDS_IV_Both1 <- MIMICIV_ARDS_IV_Combined[MIMICIV_ARDS_IV_Combined$ARDS_PF %in% c("Moderate", "Severe")  & MIMICIV_ARDS_IV_Combined$ARDS_SF %in% c("Moderate", "Severe"), ]
```


```{r}
MIMICIV_ARDS_IV_Non1 <- MIMICIV_ARDS_IV_Combined[MIMICIV_ARDS_IV_Combined$ARDS_PF %in% c("No",   "Mild")  & MIMICIV_ARDS_IV_Combined$ARDS_SF %in% c("No",   "Mild") , ]

```

```{r}
MIMICIV_IV_Berlin_ARDS1 <- MIMICIV_ARDS_IV_Combined[MIMICIV_ARDS_IV_Combined$ARDS_PF %in% c("Moderate", "Severe")  & MIMICIV_ARDS_IV_Combined$ARDS_SF %in% c("No",   "Mild") , ]

MIMICIV_IV_New_ARDS1 <- MIMICIV_ARDS_IV_Combined[MIMICIV_ARDS_IV_Combined$ARDS_PF %in% c("No",   "Mild") & MIMICIV_ARDS_IV_Combined$ARDS_SF %in% c("Moderate", "Severe"), ]
```




```{r}

character_func(MIMICIV_ARDS_IV_Both1)
```


```{r}
character_func(MIMICIV_ARDS_IV_Non1)
```

```{r}
character_func(MIMICIV_IV_Berlin_ARDS1)
```



```{r}
character_func(MIMICIV_IV_New_ARDS1)
```






